apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather_api_app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: weather_api_app
  template:
    metadata:
      labels:
        app: weather_api_app
    spec:
      containers:
      - name: django
        image: puse45/weather_api:latest
        ports:
        - containerPort: 8000
        envFrom:
        - configMapRef:
            name: weather-api-config
        livenessProbe:
          httpGet:
            path: /healthz/
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /healthz/
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: weather-api-config
data:
  DJANGO_DEBUG: "True"
  DB_HOST: "postgres-service"  # Changed from "postgres" to Kubernetes service name
  DB_PORT: "5432"
  DB_NAME: "postgres"
  DB_USER: "postgres"
  DB_PASSWORD: "postgres"
  PROJECT_NAME: "Weather API"
  ALLOWED_HOSTS: "*"
  SERVER_HOST: "http://localhost:8000"
  DEBUG: "True"
  SECRET: "django-insecure-_x9i7)-ujb#7&d6#o&ndj9)rq^4-1r=bbwmb1rhuf55(9_m^yl"
  WA_KEY: "d7a0b21daf424e3ab34125941210409"
  WA_BASE_URL: "http://api.weatherapi.com"
