apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-api-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: weather-api-app
  template:
    metadata:
      labels:
        app: weather-api-app
    spec:
      initContainers:
      - name: wait-for-db
        image: busybox:1.28
        command: ['sh', '-c', 'until nc -z postgres-service 5432; do echo "Waiting for PostgreSQL..."; sleep 2; done;']
      containers:
      - name: django
        image: puse45/weather_api:latest
        ports:
        - containerPort: 8000
        envFrom:
        - configMapRef:
            name: weather-api-config
        livenessProbe:
          httpGet:
            path: /healthz/
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /healthz/
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
