apiVersion: v1
kind: ConfigMap
metadata:
  name: weather-api-config
data:
  DJANGO_DEBUG: "True"
  DB_HOST: "postgres-service"
  DB_PORT: "5432"
  DB_NAME: "postgres"
  DB_USER: "postgres"
  DB_PASSWORD: "postgres"
  ALLOWED_HOSTS: "*"
  SERVER_HOST: "http://localhost:8000"
  DEBUG: "True"
  SECRET: "django-insecure-_x9i7)-ujb#7&d6#o&ndj9)rq^4-1r=bbwmb1rhuf55(9_m^yl"
  WA_KEY: "d7a0b21daf424e3ab34125941210409"
  WA_BASE_URL: "http://api.weatherapi.com"
